name: Deploy user_reservation_manager lambda function

on:
  push:
    paths:
      - "lambda_functions/user_reservation_manager/**"
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: create zip file for lambda function
        run: cd lambda_functions/user_reservation_manager && zip -r code.zip .

      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name user_reservation_manager \
            --zip-file fileb://lambda_functions/user_reservation_manager/code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-northeast-2"
